spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://yuanwei.com:7001/eureka/,http://yuanwei.com:7002/eureka/,http://yuanwei.com:7003/eureka/
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://yuanwei.com:8761/eureka/,http://yuanwei.com:8762/eureka/,http://yuanwei.com:8763/eureka/